name: "build_latex"

on:
  push:
    branches: 
      - '*'

env:
  MY_NAME: "firstname_lastname"

jobs:
  build_latex:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Build PDFs
      run: |
        apt-get install -y texlive-latex-recommended ghostscript
        latexmk -pdf *.tex 
        for f in *.tex; do
          ext=${f##*.}
          file=`basename $f .$ext`
          mv "$file.pdf" "${{env.MY_NAME}}_$file.pdf"
        done
        gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=${{env.MY_NAME}}_application.pdf ${{env.MY_NAME}}_*.pdf


    - name: List files in docs directory
      run: ls -R

    - name: Mark repository as safe
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Set Git user info
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "PDF BUILDER"

    - name: Check Git status
      run: git status

    - name: List tracked files
      run: git ls-files

    - name: Force add PDFs
      run: |
        git add -f *.pdf
        git status

    - name: Commit and push updated PDFs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git commit -m "Update generated PDFs" || echo "No changes to commit"
        git push
